# Generated by Django 4.0.5 on 2022-06-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.CharField(max_length=100),
        ),
    ]
